const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

(async () => {
  const baseUrl = 'http://127.0.0.1:4321';
  const pages = [
    '/',
    '/calculators/fat-loss/',
    '/calculators/bmi/',
    '/calculators/calorie/',
    '/nutrition/',
    '/blog/',
    '/glossary/'
  ];
  const viewports = [
    { name: 'desktop', width: 1440, height: 900 },
    { name: 'tablet', width: 768, height: 1024 },
    { name: 'mobile', width: 375, height: 667 }
  ];

  const results = [];
  const screenshotDir = path.join(__dirname, 'artifacts', 'screenshots');
  fs.mkdirSync(screenshotDir, { recursive: true });

  const browser = await chromium.launch({ headless: true });

  for (const vp of viewports) {
    const context = await browser.newContext({ viewport: { width: vp.width, height: vp.height } });
    const page = await context.newPage();
    for (const p of pages) {
      const url = baseUrl + p;
      const start = Date.now();
      try {
        await page.goto(url, { waitUntil: 'networkidle' });
        const loadTime = Date.now() - start;
        const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
        const slug = p.replace(/\//g, '_').replace(/^_/, '') || 'home';
        const screenshotPath = path.join(screenshotDir, `${vp.name}_${slug}.png`);
        await page.screenshot({ path: screenshotPath, fullPage: true });
        // Simple interaction for calculator pages
        let calcResult = false;
        if (p.startsWith('/calculators/')) {
          const inputs = await page.$$('[type="number"],[type="text"]');
          if (inputs.length >= 2) {
            await inputs[0].fill('70');
            await inputs[1].fill('170');
            const button = await page.$('button');
            if (button) {
              await button.click();
              await page.waitForTimeout(500);
              calcResult = true;
            }
          }
        }
        results.push({ url, viewport: vp.name, loadTime, overflow, calcResult });
      } catch (err) {
        results.push({ url, viewport: vp.name, error: err.message });
      }
    }
    await context.close();
  }

  await browser.close();

  const reportPath = path.join(__dirname, 'artifacts', 'localhost_audit_report.md');
  const lines = ['# Localhost Site Audit Report', 'Generated by Playwright script.', ''];
  for (const r of results) {
    if (r.error) {
      lines.push(`- **${r.viewport}** – ${r.url} – ❌ Error: ${r.error}`);
    } else {
      const overflowMsg = r.overflow ? '❌ Horizontal overflow' : '✅ No overflow';
      const calcMsg = r.calcResult ? '✅ Calc works' : '⚠️ No calc interaction';
      lines.push(`- **${r.viewport}** – ${r.url} – ⏱️ ${r.loadTime} ms – ${overflowMsg} ${calcMsg}`);
    }
  }
  lines.push('---', 'Screenshots saved under `artifacts/screenshots/`.');
  fs.writeFileSync(reportPath, lines.join('\n'));
  console.log('Audit complete. Report written to', reportPath);
})();
